---
- name: Main playbook to create Controller objects
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/project_vars.yml

- import_playbook: ansible_config_as_code.controller_automation.project
  vars:
    # Pass the projects_to_create variable to the imported playbook
    projects_to_create: "{{ projects_to_create }}"
