---
- name: Main playbook to create Controller objects
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Load variables from file
      include_vars: vars/project_vars.yml
      
    - name: Debugging - show projects_to_create variable
      ansible.builtin.debug:
        var: controller_projects_all
      # Check for a "success" message. If this fails, the issue is with vars_files.


# This part is to import the project.yml playbook and pass its variable.
#- import_playbook: ansible_config_as_code.controller_automation.project
- import_playbook: ansible_config_as_code.controller_automation.aap_config
  vars: 
    controller_projects_all: "{{ controller_projects_all }}"
    
  
