---
- name: Main playbook to create Controller objects
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/org_vars.yml
    - vars/project_vars.yml

# This is where import_playbook should be.
# It is at the same level as 'hosts' and 'vars_files'

- import_playbook: ansible_config_as_code.controller_automation.project
