---
- name: Main playbook to create Controller objects
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/project_vars.yml

# This part is to import the project.yml playbook and pass its variable.
- import_playbook: ansible_config_as_code.controller_automation.project
  vars:
    projects_to_create: "{{ projects_to_create }}"
